### ISSUE TITLE
Did you enable the Siri capability in your Xcode project?

### ISSUE THREAD

**Issue by OwOzZ** [Buglife/Batmobile#1]
When I built and ran your project on my device, it crashed. It logged 'Did you enable the Siri capability in your Xcode project?' error, How to solve it?? Please help me.

**Comment by schukin** [comment]
Hmmm... This looks to be an issue new to Xcode 8 beta 2. Seems that a SiriKit entitlement is now required. I'll look into it.

**Comment by schukin** [comment]
This should be fixed in 96d91f4. Can you give that a try and see if it works?

**Comment by OwOzZ** [comment]
Indeed, it is a SiriKit entitlements problem. After several cumbersome steps, I ran it on my device finally. Thank you so much.

**Comment by schukin** [comment]
Yeah, code signing w/ extensions is always fun. Glad it worked!
